name: erasml_torch

channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pygrib
  - netCDF4
  - cartopy
  - matplotlib
  - scipy
  - plotly
  - scikit-learn
  - pandas
  - numpy
  - pyproj
  - seaborn
  - notebook
  - pip
  - pip:
    - wandb
    - tqdm

